// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package common

// Error defines model for Error.
type Error struct {
	Code      int16  `json:"code"`
	Component string `json:"component"`
	Message   string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Error       `json:"error"`
	Info  Information `json:"info"`
}

// Information defines model for Information.
type Information struct {
	Name      string  `json:"name"`
	Timestamp float32 `json:"timestamp"`
	Version   string  `json:"version"`
}
