# configurations to load based on comment

Persistance:
      Driver: "pgx"
      Server: "http://localhost"
      Port: 5430
      User : "postgres"
      PassWord: "password"
HTTP:
      Port: 8081
      Prefix: "/dev"
