// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package openapi

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Info defines model for Info.
type Info struct {
	Name      *string `json:"name,omitempty"`
	TimeStamp *string `json:"timeStamp,omitempty"`
}

// Payload defines model for Payload.
type Payload = []RegisterReponse

// RegiserRequestBody defines model for RegiserRequestBody.
type RegiserRequestBody struct {
	Email     *openapi_types.Email `json:"email,omitempty"`
	FirstName *string              `json:"firstName,omitempty"`
	LastName  *string              `json:"lastName,omitempty"`
}

// RegiserResponse defines model for RegiserResponse.
type RegiserResponse struct {
	Info    *Info    `json:"info,omitempty"`
	Payload *Payload `json:"payload,omitempty"`
}

// RegisterReponse defines model for RegisterReponse.
type RegisterReponse struct {
	AccountId *int64 `json:"accountId,omitempty"`
}

// PostAccountsRegisterJSONRequestBody defines body for PostAccountsRegister for application/json ContentType.
type PostAccountsRegisterJSONRequestBody = RegiserRequestBody
