// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package openapi

// ListBooksParams defines parameters for ListBooks.
type ListBooksParams struct {
	Page  int32 `form:"page" json:"page"`
	Limit int32 `form:"limit" json:"limit"`
}
