// Package listbooks provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package listbooks

import (
	externalRef0 "github.com/srijilv/go-api-template.git/pkg/interfaces/openapi/common"
)

// ListBooksResponse defines model for ListBooksResponse.
type ListBooksResponse struct {
	Info    externalRef0.Information   `json:"info"`
	Payload []ListBooksResponsePayload `json:"payload"`
}

// ListBooksResponsePayload defines model for ListBooksResponsePayload.
type ListBooksResponsePayload struct {
	Author        string `json:"author"`
	Genre         string `json:"genre"`
	Id            int32  `json:"id"`
	Isbn          string `json:"isbn"`
	Price         string `json:"price"`
	PublishedYear int16  `json:"publishedYear"`
	Status        string `json:"status"`
	Title         string `json:"title"`
}
